[2024-04-30T16:53:54.248+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2024-04-30T16:53:43.073401+00:00 [queued]>
[2024-04-30T16:53:54.262+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2024-04-30T16:53:43.073401+00:00 [queued]>
[2024-04-30T16:53:54.263+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-04-30T16:53:54.264+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-04-30T16:53:54.265+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-04-30T16:53:54.293+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): store_user> on 2024-04-30 16:53:43.073401+00:00
[2024-04-30T16:53:54.298+0000] {standard_task_runner.py:55} INFO - Started process 631 to run task
[2024-04-30T16:53:54.303+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'manual__2024-04-30T16:53:43.073401+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpjeqe6xqi']
[2024-04-30T16:53:54.305+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask store_user
[2024-04-30T16:53:54.395+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.store_user manual__2024-04-30T16:53:43.073401+00:00 [running]> on host ec0cac6d8211
[2024-04-30T16:53:54.468+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2024-04-30T16:53:43.073401+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-30T16:53:43.073401+00:00
[2024-04-30T16:53:54.471+0000] {postgres.py:129} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2024-04-30T16:53:54.482+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2024-04-30T16:53:54.489+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/user_processing.py", line 54, in _store_user
    filename= '/tmp/processed_user.csv'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 137, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.BadCopyFileFormat: missing data for column "lastname"
CONTEXT:  COPY users, line 2: "le.com"

[2024-04-30T16:53:54.498+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=user_processing, task_id=store_user, execution_date=20240430T165343, start_date=20240430T165354, end_date=20240430T165354
[2024-04-30T16:53:54.508+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 14 for task store_user (missing data for column "lastname"
CONTEXT:  COPY users, line 2: "le.com"
; 631)
[2024-04-30T16:53:54.557+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-04-30T16:53:54.580+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
