[2024-05-03T22:35:36.994+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: covid_analytics_dag.extract_data manual__2024-05-03T22:35:08.991985+00:00 [queued]>
[2024-05-03T22:35:37.019+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: covid_analytics_dag.extract_data manual__2024-05-03T22:35:08.991985+00:00 [queued]>
[2024-05-03T22:35:37.025+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-05-03T22:35:37.028+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2024-05-03T22:35:37.029+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-05-03T22:35:37.044+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): extract_data> on 2024-05-03 22:35:08.991985+00:00
[2024-05-03T22:35:37.053+0000] {standard_task_runner.py:55} INFO - Started process 1392 to run task
[2024-05-03T22:35:37.060+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'covid_analytics_dag', 'extract_data', 'manual__2024-05-03T22:35:08.991985+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/covid_analytics.py', '--cfg-path', '/tmp/tmp1ogoyzf9']
[2024-05-03T22:35:37.061+0000] {standard_task_runner.py:83} INFO - Job 67: Subtask extract_data
[2024-05-03T22:35:37.117+0000] {task_command.py:376} INFO - Running <TaskInstance: covid_analytics_dag.extract_data manual__2024-05-03T22:35:08.991985+00:00 [running]> on host 2cb8e808f114
[2024-05-03T22:35:37.175+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Diego Munera
AIRFLOW_CTX_DAG_ID=covid_analytics_dag
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-03T22:35:08.991985+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-03T22:35:08.991985+00:00
[2024-05-03T22:35:37.186+0000] {credentials.py:1180} INFO - Found credentials in environment variables.
[2024-05-03T22:35:39.344+0000] {xcom.py:600} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2024-05-03T22:35:39.359+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/covid_analytics.py", line 34, in extract_data
    return ti.xcom_push(key='response', value=response['Payload'].read())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2385, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 212, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 597, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
[2024-05-03T22:35:39.396+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=covid_analytics_dag, task_id=extract_data, execution_date=20240503T223508, start_date=20240503T223536, end_date=20240503T223539
[2024-05-03T22:35:39.416+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 67 for task extract_data (Object of type bytes is not JSON serializable; 1392)
[2024-05-03T22:35:39.517+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-05-03T22:35:39.586+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
